# Generated by Django 4.1.7 on 2023-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_brand_name_alter_product_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='size',
            name='unique_product_name',
        ),
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('name',), name='unique_size_name'),
        ),
    ]
