# Generated by Django 4.1.7 on 2023-04-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_size_unique_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='size',
            name='unique_size_name',
        ),
    ]
