# Generated by Django 4.1.7 on 2023-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_remove_size_unique_size_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('name',), name='unique_size_name'),
        ),
    ]
